# Generated by Django 2.2.5 on 2021-06-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A pagar', 'A pagar'), ('A receber', 'A receber')], max_length=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_vencimento', models.DateField()),
                ('tipo_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('Boleto', 'Boleto')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
