# Generated by Django 3.2 on 2021-06-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_auto_20210607_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='id',
        ),
        migrations.AddField(
            model_name='conta',
            name='cod_Conta',
            field=models.AutoField(default=2, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
