# Generated by Django 3.2 on 2021-06-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20210609_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cod_Conta',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
