# Generated by Django 3.2 on 2021-06-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_conta_cod_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cod_Conta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
