# Generated by Django 3.2 on 2021-05-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=10)),
                ('qntd', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=3)),
                ('preco_compra', models.FloatField(default=0)),
                ('preco_venda', models.FloatField(default=0)),
            ],
        ),
    ]
