# Generated by Django 3.2 on 2021-06-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0003_fornecedor_telefone2'),
        ('produtos', '0002_auto_20210607_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
        ),
    ]
