# Generated by Django 3.2 on 2021-06-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210607_2213'),
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.CharField(default='N tem email ainda', max_length=30),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereço',
            field=models.CharField(default='N tem endereco ainda', max_length=70),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(default='N tem nome ainda', max_length=30),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(to='produtos.Produto'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone1',
            field=models.CharField(default='N tem telefone ainda', max_length=11),
        ),
    ]
