# Generated by Django 3.2 on 2021-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_auto_20210608_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='telefone2',
            field=models.CharField(blank=True, default='N tem telefone ainda', max_length=11, null=True),
        ),
    ]
