# Generated by Django 2.2.5 on 2021-06-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
    ]
