# Generated by Django 3.2 on 2021-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('telefone1', models.CharField(max_length=11)),
                ('telefone2', models.CharField(blank=True, max_length=11, null=True)),
                ('endereço', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.CharField(max_length=40)),
                ('data_nascimento', models.DateField(verbose_name='aniversário')),
                ('cargo', models.CharField(max_length=15)),
            ],
        ),
    ]
