# Generated by Django 2.2.5 on 2021-06-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('veiculos', '0002_veiculo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('numeroOS', models.IntegerField(primary_key=True, serialize=False)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('valor', models.FloatField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em andamento', 'Em andamento'), ('Feito', 'Feito')], max_length=50, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Cliente')),
                ('veiculos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.Veiculo')),
            ],
        ),
    ]
