# Generated by Django 2.2.5 on 2021-06-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='numeroOS',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
