# Generated by Django 3.2 on 2021-06-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_nome_fornecedor'),
        ('funcionario', '0001_initial'),
        ('ordemServico', '0002_auto_20210607_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, to='produtos.Produto'),
        ),
    ]
